#index:
#    path: /
#    controller: App\Controller\DefaultController::index
laskePalkka:
    path: /esimerkki/esim1
    controller: App\Controller\EsimerkkiController::laskePalkka

laskePH:
    path: /esimerkki/esim3
    controller: App\Controller\EsimerkkiController::laskePH